apiVersion: v2
appVersion: "1.0"
dependencies:
- name: orc8rlib
  repository: file://../../../../orc8r/cloud/helm/orc8rlib
  version: 0.1.2
description: A Helm chart for magma orchestrator's lte module
keywords:
- magma
- or8cr
- lte-orc8r
name: lte-orc8r
sources:
- https://github.com/magma/magma
version: 0.2.5
