apiVersion: v1
appVersion: "1.0"
description: A Helm chart for log aggregation infrastructure
keywords:
- magma
- orc8r
- logging
name: logging
sources:
- https://github.com/magma/magma
version: 0.1.10
